### ISSUE TITLE
WinPhone: Platform implementation not found.  

### ISSUE THREAD

**Issue by blocksninja** [aritchie/deviceinfo#4]
I'm unable to use the library on WinPhone (in Xamarin.Forms).
The following error occures: 
"Platform implementation not found.  Have you added a nuget reference to your platform project?"

Stacktrace:
<code>   at Acr.DeviceInfo.DeviceInfo.<>c.<.cctor>b__20_3()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Acr.DeviceInfo.DeviceInfo.get_Hardware()
   at Pingtown.PageModels.LoginPageModel.ViewIsAppearing(Object sender, EventArgs e)
   at Xamarin.Forms.Page.SendAppearing()
   at Xamarin.Forms.Platform.WinPhone.PageRenderer.<OnElementChanged>b__1(Object sender, RoutedEventArgs args)
   at MS.Internal.CoreInvokeHandler.InvokeEventHandler(Int32 typeIndex, Delegate handlerDelegate, Object sender, Object args)
   at MS.Internal.JoltHelper.FireEvent(IntPtr unmanagedObj, IntPtr unmanagedObjArgs, Int32 argsTypeIndex, Int32 actualArgsTypeIndex, String eventName)</code

**Comment by aritchie** [comment]
Have you installed the nuget package into your winphone project as well?

**Comment by tjanela** [comment]
I can replicate this issue if the target is Windows Phone 8.0
If the target is Windows Phone 8.1 it runs fine.
@aritchie please advise.

**Comment by aritchie** [comment]
I only support wp81.

**Comment by tjanela** [comment]
Thanks @aritchie!
@timbrand do you confirm my results?
